import Disaster from "../models/disasterEventModel.js";
import Resource from "../models/recoveryNeedModel.js";
import ActivityLog from "../models/activityLogModel.js";
import { calculateSeverity } from "../utils/calculateSeverity.js";
import { buildDisasterPayload } from "../utils/disasterPayLoad.js";
import { calculateResources } from "../services/calculationServices.js";

const ML_API_URL = process.env.ML_API_URL || "http://localhost:8000";

const predictAndSave = async (req, res) => {
  try {
    const {
      title,
      description,
      startDate,
      duration_days = 7,
      ...mlFeatures
    } = req.body;

    const mlResponse = await fetch(`${ML_API_URL}/predict`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(mlFeatures),
    });

    if (!mlResponse.ok) {
      const errBody = await mlResponse.json().catch(() => ({}));
      return res.status(502).json({
        success: false,
        message: "ML service error",
        detail: errBody.detail || mlResponse.statusText,
      });
    }

    const { predictions } = await mlResponse.json();

    const typeMap = {
      Flood: "Flood",
      Earthquake: "Earthquake",
      Drought: "Drought",
      Wildfire: "Wildfire",
      Cyclone: "Cyclone",
      Heatwave: "Heatwave",
    };
    const disasterType = typeMap[mlFeatures.disaster_type] || "Other";

    const autoTitle =
      title ||
      `${disasterType} — ${mlFeatures.province} (${new Date().toLocaleDateString("en-PK")})`;

    const payload = {
      title: autoTitle,
      description: description || `AI-predicted impact for ${autoTitle}.`,
      disasterType,
      status: "Ongoing",
      startDate: startDate ? new Date(startDate) : new Date(),
      country: "Pakistan",
      province: mlFeatures.province,
      location: {
        type: "Point",
        coordinates: [
          Number(mlFeatures.longitude),
          Number(mlFeatures.latitude),
        ],
      },
      impact: {
        deaths: Math.round(predictions.deaths),
        injured: Math.round(predictions.injured),
        affected_population: Math.round(predictions.affected_population),
        houses_damaged: Math.round(predictions.houses_damaged),
        houses_demolished: Math.round(predictions.houses_demolished),
        crop_area_damaged: Math.round(predictions.crop_area_damaged),
      },
      technicalData: {
        magnitude: mlFeatures.magnitude || undefined,
        river_discharge_cusecs: mlFeatures.river_discharge_cusecs || undefined,
        temperature_max: mlFeatures.temperature_max || undefined,
      },
    };

    payload.createdBy = req.user._id;

    payload.severity = calculateSeverity(payload.impact);

    const disaster = new Disaster(payload);
    const saved = await disaster.save();

    await ActivityLog.log({
      userId: req.user._id,
      userRole: req.user.role,
      category: "disaster",
      action: "PREDICTED",
      target: { model: "DisasterEvent", id: saved._id },
      description: `AI prediction created for ${saved.disasterType} in ${saved.province} — severity: ${saved.severity}`,
      req,
      statusCode: 201,
      success: true,
      metadata: {
        disasterType: saved.disasterType,
        province: saved.province,
        severity: saved.severity,
        mlPredictions: predictions,
        resourcesAutoGenerated: false,
      },
    });

    return res.status(201).json({
      success: true,
      predictions,
      disaster: saved,
      message: "Disaster predicted and saved. Resources can be added by NGOs.",
    });
  } catch (error) {
    console.error("[predictAndSave]", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

const syncResourceRecord = async (disaster, duration = 7) => {
  const calc = calculateResources({
    affected_population: disaster.impact.affected_population,
    injured: disaster.impact.injured,
    houses_damaged: disaster.impact.houses_damaged,
    houses_demolished: disaster.impact.houses_demolished,
    duration_days: duration,
    province: disaster.province,
  });

  return Resource.findOneAndUpdate(
    { disasterId: disaster._id },
    {
      disasterId: disaster._id,
      region: disaster.province,
      affected_population: calc.executive_summary.total_population,
      households: calc.executive_summary.total_households,
      water_liters: calc.detailed_resources.water_liters,
      food_kg: calc.detailed_resources.food_kg,
      food_tons: calc.logistics.total_food_tons,
      shelter: calc.detailed_resources.shelter,
      nfi: calc.detailed_resources.nfi_kits,
      health: calc.detailed_resources.health,
      sanitation: calc.detailed_resources.sanitation,
      logistics: {
        trucks_required: calc.logistics.trucks_required,
        storage_space_sqft: calc.logistics.storage_space_sqft,
      },
    },
    { returnDocument: "after", upsert: true, setDefaultsOnInsert: true },
  );
};

const createDisaster = async (req, res) => {
  try {
    const { duration_days = 7, ...rest } = req.body;
    const payload = buildDisasterPayload(rest, req.user._id);

    payload.severity = calculateSeverity(payload.impact || {});

    const disaster = new Disaster(payload);
    const saved = await disaster.save();


    await ActivityLog.log({
      userId: req.user._id,
      userRole: req.user.role,
      category: "disaster",
      action: "CREATED",
      target: { model: "DisasterEvent", id: saved._id },
      description: `Created ${saved.disasterType} disaster in ${saved.province} - severity: ${saved.severity}`,
      req,
      statusCode: 201,
      success: true,
      metadata: {
        disasterType: saved.disasterType,
        province: saved.province,
        severity: saved.severity,
        resourcesSaved: false,
      },
    });

    res.status(201).json({
      success: true,
      disaster: saved,
      resources: resourceRecord,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

const getAllDisasters = async (req, res) => {
  try {
    const disasters = await Disaster.find().sort({ createdAt: -1 });

    res.json({
      success: true,
      count: disasters.length,
      data: disasters,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

const getDisasterById = async (req, res) => {
  try {
    const disaster = await Disaster.findById(req.params.id);

    if (!disaster) {
      return res
        .status(404)
        .json({ success: false, message: "Disaster not found." });
    }

    const resources = await Resource.findOne({ disasterId: disaster._id });

    await ActivityLog.log({
      userId: req.user._id,
      userRole: req.user.role,
      category: "disaster",
      action: "VIEWED",
      target: { model: "DisasterEvent", id: disaster._id },
      description: `Viewed ${disaster.disasterType} disaster in ${disaster.province}`,
      req,
      statusCode: 200,
      success: true,
    });

    res.json({ success: true, disaster, resources: resources || null });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

const getFilteredDisasters = async (req, res) => {
  try {
    const { fromDate, toDate, region, disasterType, severity, status } =
      req.query;

    const query = {};

    if (fromDate || toDate) {
      query.startDate = {};
      if (fromDate) query.startDate.$gte = new Date(fromDate);
      if (toDate) query.startDate.$lte = new Date(toDate);
    }

    if (region && region !== "all") {
      query.province = new RegExp(`^${region}$`, "i");
    }

    if (disasterType && disasterType !== "all") {
      query.disasterType = disasterType;
    }

    if (status && status !== "all") {
      const statusMap = {
        active: "Ongoing",
        resolved: "Terminated",
        monitoring: "Contained",
      };
      query.status = statusMap[status] || status;
    }

    if (severity && severity !== "all") {
      query.severity =
        severity.charAt(0).toUpperCase() + severity.slice(1).toLowerCase();
    }

    const disasters = await Disaster.find(query).sort({ startDate: -1 });

    res.json({
      success: true,
      count: disasters.length,
      data: disasters,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

const getMonthlyStats = async (req, res) => {
  try {
    const start = new Date();
    start.setDate(1);
    start.setHours(0, 0, 0, 0);

    const end = new Date();

    const disasters = await Disaster.find({
      startDate: { $gte: start, $lte: end },
    });

    let totalAffected = 0;
    const regionStats = {};
    const severityBreakdown = { Low: 0, Medium: 0, High: 0 };
    const typeBreakdown = {};

    disasters.forEach((d) => {
      const affected = d.impact?.affected_population || 0;
      totalAffected += affected;

      if (!regionStats[d.province]) regionStats[d.province] = 0;
      regionStats[d.province] += affected;

      const sev = d.severity || calculateSeverity(d.impact);
      if (severityBreakdown[sev] !== undefined) severityBreakdown[sev]++;

      if (!typeBreakdown[d.disasterType]) typeBreakdown[d.disasterType] = 0;
      typeBreakdown[d.disasterType]++;
    });

    res.json({
      success: true,
      totalAffected,
      regionStats,
      severityBreakdown,
      typeBreakdown,
      totalDisasters: disasters.length,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

const updateDisaster = async (req, res) => {
  try {
    const { duration_days, ...body } = req.body;

    const disaster = await Disaster.findById(req.params.id);
    if (!disaster) {
      return res
        .status(404)
        .json({ success: false, message: "Disaster not found." });
    }

    const allowedFields = [
      "status",
      "endDate",
      "impact",
      "technicalData",
      "description",
    ];
    const updates = {};

    allowedFields.forEach((field) => {
      if (body[field] !== undefined) updates[field] = body[field];
    });

    let impactChanged = false;
    if (updates.impact) {
      updates.impact = { ...disaster.impact.toObject(), ...updates.impact };
      updates.severity = calculateSeverity(updates.impact);
      impactChanged = true;
    }

    const updated = await Disaster.findByIdAndUpdate(req.params.id, updates, {
      new: true,
      runValidators: true,
    });

    let resourceRecalculationNeeded = false;
    if (impactChanged) {
      resourceRecalculationNeeded = true;

      await ActivityLog.log({
        userId: req.user._id,
        userRole: req.user.role,
        category: "disaster",
        action: "IMPACT_UPDATED",
        target: { model: "DisasterEvent", id: updated._id },
        description: `Impact updated for ${updated.disasterType} in ${updated.province}. NGOs should recalculate resources if needed.`,
        req,
        statusCode: 200,
        success: true,
        metadata: {
          disasterId: updated._id,
          impactChanged: true,
          resourceRecalculationNeeded: true,
        },
      });
    }

    await ActivityLog.log({
      userId: req.user._id,
      userRole: req.user.role,
      category: "disaster",
      action: "UPDATED",
      target: { model: "DisasterEvent", id: updated._id },
      description: `Updated ${updated.disasterType} disaster in ${updated.province}`,
      req,
      statusCode: 200,
      success: true,
      metadata: {
        updatedFields: Object.keys(updates),
        resourcesNeedRecalculation: impactChanged,
      },
    });

    res.json({
      success: true,
      disaster: updated,
      message: impactChanged
        ? "Disaster updated. Resources may need recalculation by NGOs."
        : "Disaster updated successfully.",
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

const deleteDisaster = async (req, res) => {
  try {
    const deleted = await Disaster.findByIdAndDelete(req.params.id);

    if (!deleted) {
      return res
        .status(404)
        .json({ success: false, message: "Disaster not found." });
    }

    await Resource.deleteOne({ disasterId: deleted._id });

    await ActivityLog.log({
      userId: req.user._id,
      userRole: req.user.role,
      category: "disaster",
      action: "DELETED",
      target: { model: "DisasterEvent", id: deleted._id },
      description: `Deleted ${deleted.disasterType} disaster in ${deleted.province} (resources also removed)`,
      req,
      statusCode: 200,
      success: true,
      metadata: {
        disasterType: deleted.disasterType,
        province: deleted.province,
      },
    });

    res.json({
      success: true,
      message: "Disaster and its resource record deleted successfully.",
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

const getMyDisasters = async (req, res) => {
  try {
    const disasterCount = await Disaster.countDocuments({
      createdBy: req.user._id,
    });

    if (!disasterCount) {
      return res
        .status(404)
        .json({ success: false, message: "Disaster not found." });
    }

    await ActivityLog.log({
      userId: req.user._id,
      userRole: req.user.role,
      category: "disaster",
      action: "VIEWED",
      target: { model: "DisasterEvent" },
      description: `${req.user._id} Viewed his total disaster predictions: ${disasterCount}`,
      req,
      statusCode: 200,
      success: true,
    });

    res.json({
      success: true,
      disasterCount,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export {
  createDisaster,
  getAllDisasters,
  getDisasterById,
  getFilteredDisasters,
  getMonthlyStats,
  updateDisaster,
  deleteDisaster,
  predictAndSave,
  getMyDisasters,
};
